### ISSUE TITLE
How to set FirstRunDelay?

### ISSUE THREAD

**Issue by CribAd** [justdmitry/RecurrentTasks#10]
In my ConfigureServices I have:

`services.AddTask<UpdateElements>(o => o.AutoStart(TimeSpan.FromSeconds(30)));`

And my method looks like:

    public class UpdateElements: IRunnable
    {
        private readonly IElementRepository _elementRepository;

        public UpdateElements(IElementRepository elementRepository)
        {
            _elementRepository= elementRepository;
        }

        public Task RunAsync(ITask currentTask, IServiceProvider scopeServiceProvider, CancellationToken cancellationToken)
        {            
            return Task.Run(() => {
                _elementRepository.UpdateElements();
            });
        }
    }

Now I want to delay the first time with 5 minutes using FirstRunDelay. Where do I need to set this option?

**Comment by justdmitry** [comment]
Add second param to AutoStart:

```
services.AddTask<UpdateElements>(o => o.AutoStart(TimeSpan.FromSeconds(30), TimeSpan.FromMinutes(5)));
```

**Comment by CribAd** [comment]
Thanks, that was the missing link.
