### ISSUE TITLE
Unexpected Cancellation

### ISSUE THREAD

**Issue by CribAd** [justdmitry/RecurrentTasks#11]
Hi,

I'm experiencing problems with RecurrentTasks. It looks like sometimes a RecurrentTask stops unexpected. In the logfile I find the warning "CancellationToken signaled, stopping...". 

But I don't use a CancellationToken. How can I debug why a Recurrent Task is cancelled?

**Comment by justdmitry** [comment]
It's internal `CancellationToken`, that can be signaled by:

1) When external (provided in `Start()`) CancellationToken is signaled
2) When you call `Stop()` on `ITask<...>`
3) When you set `Options.Interval` to Zero
