### ISSUE TITLE
Getting an inner task type name from a TaskRunner

### ISSUE THREAD

**Issue by a-a-k** [justdmitry/RecurrentTasks#6]
Logging with the code below

![image](https://user-images.githubusercontent.com/5455861/45941291-ad52f800-c007-11e8-8a1c-76811a18eadb.png)

Giving the next result
![image](https://user-images.githubusercontent.com/5455861/45941303-bba11400-c007-11e8-8458-477d1c447303.png)

**Comment by justdmitry** [comment]
Since v6, you may use `task.RunnableType` (gives you `typeof(TRunnable)`)

**Comment by justdmitry** [comment]
Oops, changed a bit, final commit is 17a784cce58171e8c8d39010bab20703846ec8c3
