### ISSUE TITLE
Why do we provide the ServiceProvider to the task implementation?

### ISSUE THREAD

**Issue by VictorioBerra** [justdmitry/RecurrentTasks#9]
https://github.com/justdmitry/RecurrentTasks/blob/912839b538d8c1cea5b91d030344f4b059da03c6/src/RecurrentTasks/TaskRunner.cs#L207

People can ask for deps in the ctor of their `IRunnable` implementation, so why provide the `ServiceProvider` to the users `RunAsnc`?

**Comment by justdmitry** [comment]
For receiving scope-wide services when task (itself) is registered as singleton.

**Comment by VictorioBerra** [comment]
Ahhh, thanks!
